language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  - TEST_CMD=test
  - TEST_CMD=lint
before_script:
  - npm install -g grunt-cli
  - npm install sequelize
script:
  - grunt travis --stack
after_script:
  - if [ "$TEST_CMD" = 'test' ]; then npm run coveralls; fi
