language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=test
before_script:
  - npm i -g grunt-cli
  - npm i sequelize
script:
  - grunt validate
  - npm run-script coverage
after_script:
  - npm run-script coveralls
